# Generated by Django 5.2.6 on 2025-09-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='removed',
            new_name='deleted',
        ),
    ]
