# Generated by Django 5.2.6 on 2025-09-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
    ]
