# Generated by Django 5.2.6 on 2025-09-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_alter_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
